import Erdos249257.GenericTailOrbitRigidity
import Erdos249257.LcmDiagonalReduction
import Erdos249257.MersenneLambertLadder
import Mathlib.Tactic

/-!
# LCM factor-ideal anchor-pulse obstruction

The clean LCM-ray factorisation exposes useful arithmetic, but retaining only
its homogeneous factors does not force the binary carry to escape.  This
module gives an explicit nonzero all-horizon countermodel.  Its letters are
multiples of `φ(periodLcm t)`, it agrees with every exact whole-ray anchor
`deltaTotient H (q * H) = φ(H)` for `2 ≤ q < t`, and both its letters and
states stay inside the natural diagonal bounds.  More strongly, the same
countermodel survives every finite integer shift polynomial.  This includes
every commensurate finite-rank LCM cube through the normal form
`P_m(E_H) * ∏ (E_H^n - 1)` and therefore closes the finite-rank shift-algebra
route, not only one rank-two or rank-three instance.

The countermodel is synthetic: it does not claim that the compensation
letters occur as actual totient differences.  Its role is to close the
factor-only implication.  The arithmetic information which survives this
no-go is the recursive quotient identity
`deltaTotient_periodLcm_ray_split` in `LcmDiagonalReduction`.  The final
section also decomposes the actual totient into Möbius divisor channels and
proves the exact old-channel cancellation threshold: two shift axes divisible
by `d` annihilate the `d`-channel.  Thus an actual proof must control the
fresh channels which evade that threshold.
-/

set_option maxRecDepth 10000

namespace Erdos249257
namespace TotientTailPeriodKiller

open Finset

/-! ## Generic sparse pulses inside the existing affine-orbit owner -/

/-- A state which is `-A` on a finite anchor set and zero elsewhere. -/
def sparsePulseState (A : ℤ) (S : Finset ℕ) (k : ℕ) : ℤ :=
  if k ∈ S then -A else 0

/-- The zero-based forcing letter determined by `c_{i+1} = 2c_i - a_i`. -/
def sparsePulseLetter (A : ℤ) (S : Finset ℕ) (i : ℕ) : ℤ :=
  2 * sparsePulseState A S i - sparsePulseState A S (i + 1)

/-- The one-based input convention used by `affineBinaryOrbit`. -/
def sparsePulseInput (A : ℤ) (S : Finset ℕ) : ℕ → ℤ
  | 0 => 0
  | i + 1 => sparsePulseLetter A S i

/-- Sparse pulses satisfy the forced affine recurrence by construction. -/
theorem sparsePulse_recurrence (A : ℤ) (S : Finset ℕ) (i : ℕ) :
    sparsePulseState A S (i + 1) =
      2 * sparsePulseState A S i - sparsePulseLetter A S i := by
  unfold sparsePulseLetter
  ring

/-- The synthetic state is exactly an instance of the existing generic
`affineBinaryOrbit`; this module does not introduce a second orbit theory. -/
theorem affineBinaryOrbit_sparsePulseInput (A : ℤ) (S : Finset ℕ) :
    ∀ k : ℕ,
      affineBinaryOrbit (sparsePulseInput A S) (sparsePulseState A S 0) k =
        sparsePulseState A S k := by
  intro k
  induction k with
  | zero => rfl
  | succ k ih =>
      rw [affineBinaryOrbit_succ, ih]
      simp [sparsePulseInput, sparsePulseLetter]

/-- Every sparse-pulse letter lies in the principal ideal generated by `A`. -/
theorem sparsePulse_dvd_letter (A : ℤ) (S : Finset ℕ) (i : ℕ) :
    A ∣ sparsePulseLetter A S i := by
  unfold sparsePulseLetter sparsePulseState
  split <;> split <;> simp

/-- The state has magnitude at most the pulse amplitude. -/
theorem abs_sparsePulseState_le (A : ℤ) (S : Finset ℕ) (k : ℕ) :
    |sparsePulseState A S k| ≤ |A| := by
  by_cases hk : k ∈ S <;> simp [sparsePulseState, hk]

/-- The forcing letter has magnitude at most twice the pulse amplitude. -/
theorem abs_sparsePulseLetter_le (A : ℤ) (S : Finset ℕ) (i : ℕ) :
    |sparsePulseLetter A S i| ≤ 2 * |A| := by
  by_cases hi : i ∈ S <;> by_cases hs : i + 1 ∈ S
  all_goals simp [sparsePulseLetter, sparsePulseState, hi, hs, abs_mul]
  all_goals have hA : 0 ≤ |A| := abs_nonneg A
  all_goals ring_nf
  all_goals simp only [abs_neg] at *
  all_goals omega

/-! ## Dyadic coboundaries and finite shift rank

The sparse pulse is not merely one recurrence counterexample.  It lies in the
image of the dyadic coboundary `2 - E`, and that image is stable under every
finite composition of additive shift differences.  This is the exact
algebraic reason that adding finitely many LCM-cube rows cannot by itself
remove the terminal-state compensation.
-/

/-- The zero-based dyadic coboundary `(2 - E)c`. -/
def dyadicCoboundary (c : ℕ → ℤ) (n : ℕ) : ℤ :=
  2 * c n - c (n + 1)

/-- The depth-`L` cleared binary prefix, accumulated from left to right.
Equivalently this is `∑ j < L, a (n+j) * 2^(L-1-j)`. -/
def dyadicClearedPrefix (a : ℕ → ℤ) (n : ℕ) : ℕ → ℤ
  | 0 => 0
  | L + 1 => 2 * dyadicClearedPrefix a n L + a (n + L)

/-- A dyadic coboundary has exact prefix/terminal-state cancellation at every
start and every finite horizon. -/
theorem dyadicClearedPrefix_dyadicCoboundary (c : ℕ → ℤ) (n L : ℕ) :
    dyadicClearedPrefix (dyadicCoboundary c) n L =
      (2 : ℤ) ^ L * c n - c (n + L) := by
  induction L with
  | zero => simp [dyadicClearedPrefix]
  | succ L ih =>
      rw [dyadicClearedPrefix, ih]
      simp only [dyadicCoboundary, pow_succ]
      rw [show n + L + 1 = n + (L + 1) by omega]
      ring

/-- Additive forward difference with step `h`. -/
def forwardDifference (h : ℕ) (f : ℕ → ℤ) (n : ℕ) : ℤ :=
  f (n + h) - f n

/-- An arbitrary finite-rank additive cube, represented as a list of shift
steps.  Repeated steps and noncommensurate steps are both allowed. -/
def iteratedForwardDifference : List ℕ → (ℕ → ℤ) → (ℕ → ℤ)
  | [], f => f
  | h :: hs, f => forwardDifference h (iteratedForwardDifference hs f)

/-- Additive forward differences commute. -/
theorem forwardDifference_comm (h k : ℕ) (f : ℕ → ℤ) :
    forwardDifference h (forwardDifference k f) =
      forwardDifference k (forwardDifference h f) := by
  funext n
  simp only [forwardDifference]
  rw [show n + h + k = n + k + h by omega]
  ring

/-- One forward difference commutes with an arbitrary finite list of the
others. -/
theorem forwardDifference_iteratedForwardDifference
    (h : ℕ) (shifts : List ℕ) (f : ℕ → ℤ) :
    forwardDifference h (iteratedForwardDifference shifts f) =
      iteratedForwardDifference shifts (forwardDifference h f) := by
  induction shifts with
  | nil => rfl
  | cons k shifts ih =>
      simp only [iteratedForwardDifference]
      rw [forwardDifference_comm h k, ih]

/-- Splitting a shift list splits the corresponding operator composition. -/
theorem iteratedForwardDifference_append
    (left right : List ℕ) (f : ℕ → ℤ) :
    iteratedForwardDifference (left ++ right) f =
      iteratedForwardDifference left (iteratedForwardDifference right f) := by
  induction left with
  | nil => rfl
  | cons h left ih =>
      simp only [List.cons_append, iteratedForwardDifference]
      rw [ih]

/-- Every finite shift list preserves the zero sequence. -/
theorem iteratedForwardDifference_zero (shifts : List ℕ) :
    iteratedForwardDifference shifts (fun _ => 0) = fun _ => 0 := by
  induction shifts with
  | nil => rfl
  | cons h shifts ih =>
      simp only [iteratedForwardDifference, ih]
      funext n
      simp [forwardDifference]

/-- One shift difference commutes with the dyadic coboundary. -/
theorem forwardDifference_dyadicCoboundary (h : ℕ) (c : ℕ → ℤ) :
    forwardDifference h (dyadicCoboundary c) =
      dyadicCoboundary (forwardDifference h c) := by
  funext n
  simp only [forwardDifference, dyadicCoboundary]
  rw [show n + h + 1 = n + 1 + h by omega]
  ring

/-- Every finite-rank additive cube preserves the coboundary class. -/
theorem iteratedForwardDifference_dyadicCoboundary
    (shifts : List ℕ) (c : ℕ → ℤ) :
    iteratedForwardDifference shifts (dyadicCoboundary c) =
      dyadicCoboundary (iteratedForwardDifference shifts c) := by
  induction shifts with
  | nil => rfl
  | cons h hs ih =>
      simp only [iteratedForwardDifference]
      rw [ih, forwardDifference_dyadicCoboundary]

/-- Exact all-rank, all-horizon cancellation.  The cleared residue of any
finite additive cube is precisely the negative terminal transformed state
modulo `2^L`. -/
theorem iteratedForwardDifference_dyadicClearedPrefix
    (shifts : List ℕ) (c : ℕ → ℤ) (n L : ℕ) :
    dyadicClearedPrefix
        (iteratedForwardDifference shifts (dyadicCoboundary c)) n L =
      (2 : ℤ) ^ L * iteratedForwardDifference shifts c n -
        iteratedForwardDifference shifts c (n + L) := by
  rw [iteratedForwardDifference_dyadicCoboundary]
  exact dyadicClearedPrefix_dyadicCoboundary _ _ _

/-- Principal ideals are preserved by arbitrary finite additive rank. -/
theorem dvd_iteratedForwardDifference (d : ℤ) (f : ℕ → ℤ)
    (hdiv : ∀ n, d ∣ f n) (shifts : List ℕ) (n : ℕ) :
    d ∣ iteratedForwardDifference shifts f n := by
  induction shifts generalizing n with
  | nil => exact hdiv n
  | cons h hs ih =>
      simp only [iteratedForwardDifference, forwardDifference]
      exact (ih (n + h)).sub (ih n)

/-- A uniform bound grows by at most `2^rank` under a finite additive cube. -/
theorem abs_iteratedForwardDifference_le (f : ℕ → ℤ) (B : ℤ)
    (hB : ∀ n, |f n| ≤ B) (shifts : List ℕ) (n : ℕ) :
    |iteratedForwardDifference shifts f n| ≤
      (2 : ℤ) ^ shifts.length * B := by
  induction shifts generalizing n with
  | nil => simpa [iteratedForwardDifference] using hB n
  | cons h hs ih =>
      simp only [iteratedForwardDifference, forwardDifference, List.length_cons]
      calc
        |iteratedForwardDifference hs f (n + h) -
            iteratedForwardDifference hs f n| ≤
            |iteratedForwardDifference hs f (n + h)| +
              |iteratedForwardDifference hs f n| := abs_sub _ _
        _ ≤ (2 : ℤ) ^ hs.length * B + (2 : ℤ) ^ hs.length * B :=
          add_le_add (ih (n + h)) (ih n)
        _ = (2 : ℤ) ^ (hs.length + 1) * B := by rw [pow_succ]; ring

/-! A finite shift polynomial is more general than a pure cube: its
coefficients also cover the geometric factor
`P_m(E_H) = 1 + E_H + ⋯ + E_H^(m-1)` which appears when a commensurate
cube is expressed through one scalar `H`-difference. -/

/-- Evaluation of a finite integer shift polynomial on a sequence.  A term
`(h, q)` contributes `q * f(n+h)`. -/
def shiftLinearCombination : List (ℕ × ℤ) → (ℕ → ℤ) → (ℕ → ℤ)
  | [], _ => fun _ => 0
  | (h, q) :: terms, f => fun n =>
      q * f (n + h) + shiftLinearCombination terms f n

/-- The `ℓ1` weight of a finite shift polynomial. -/
def shiftLinearWeight : List (ℕ × ℤ) → ℤ
  | [] => 0
  | (_, q) :: terms => |q| + shiftLinearWeight terms

/-- The dyadic coboundary commutes with every finite integer shift
polynomial, not only products of forward differences. -/
theorem shiftLinearCombination_dyadicCoboundary
    (terms : List (ℕ × ℤ)) (c : ℕ → ℤ) :
    shiftLinearCombination terms (dyadicCoboundary c) =
      dyadicCoboundary (shiftLinearCombination terms c) := by
  induction terms with
  | nil =>
      funext n
      simp [shiftLinearCombination, dyadicCoboundary]
  | cons term terms ih =>
      rcases term with ⟨h, q⟩
      funext n
      simp only [shiftLinearCombination, dyadicCoboundary]
      rw [congrFun ih n]
      simp only [dyadicCoboundary]
      rw [show n + h + 1 = n + 1 + h by omega]
      ring

/-- Exact prefix/terminal cancellation for an arbitrary finite shift
polynomial. -/
theorem shiftLinearCombination_dyadicClearedPrefix
    (terms : List (ℕ × ℤ)) (c : ℕ → ℤ) (n L : ℕ) :
    dyadicClearedPrefix
        (shiftLinearCombination terms (dyadicCoboundary c)) n L =
      (2 : ℤ) ^ L * shiftLinearCombination terms c n -
        shiftLinearCombination terms c (n + L) := by
  rw [shiftLinearCombination_dyadicCoboundary]
  exact dyadicClearedPrefix_dyadicCoboundary _ _ _

/-- Principal ideals are preserved by arbitrary finite integer shift
polynomials. -/
theorem dvd_shiftLinearCombination (d : ℤ) (f : ℕ → ℤ)
    (hdiv : ∀ n, d ∣ f n) (terms : List (ℕ × ℤ)) (n : ℕ) :
    d ∣ shiftLinearCombination terms f n := by
  induction terms with
  | nil => simp [shiftLinearCombination]
  | cons term terms ih =>
      rcases term with ⟨h, q⟩
      simp only [shiftLinearCombination]
      exact (dvd_mul_of_dvd_right (hdiv (n + h)) q).add ih

/-- A finite shift polynomial enlarges a uniform bound by at most the
`ℓ1`-weight of its coefficients. -/
theorem abs_shiftLinearCombination_le (f : ℕ → ℤ) (B : ℤ)
    (hB : ∀ n, |f n| ≤ B) (terms : List (ℕ × ℤ)) (n : ℕ) :
    |shiftLinearCombination terms f n| ≤ shiftLinearWeight terms * B := by
  induction terms with
  | nil => simp [shiftLinearCombination, shiftLinearWeight]
  | cons term terms ih =>
      rcases term with ⟨h, q⟩
      simp only [shiftLinearCombination, shiftLinearWeight]
      calc
        |q * f (n + h) + shiftLinearCombination terms f n| ≤
            |q * f (n + h)| + |shiftLinearCombination terms f n| := abs_add_le _ _
        _ = |q| * |f (n + h)| + |shiftLinearCombination terms f n| := by
          rw [abs_mul]
        _ ≤ |q| * B + shiftLinearWeight terms * B :=
          add_le_add (mul_le_mul_of_nonneg_left (hB (n + h)) (abs_nonneg q)) ih
        _ = (|q| + shiftLinearWeight terms) * B := by ring

/-! ## Actual totient channels: the precise old/fresh boundary -/

/-- The `d`-th Möbius channel in
`φ(n) = ∑_{d∣n} μ(d) (n/d)`, totalized by zero off the divisor
progression. -/
def mobiusTotientChannel (d n : ℕ) : ℤ :=
  if d ∣ n then
    ArithmeticFunction.moebius d * ((n / d : ℕ) : ℤ)
  else 0

/-- The channel definition reconstructs the actual totient on its finite
divisor support. -/
theorem totient_eq_sum_mobiusTotientChannel (n : ℕ) (hn : 0 < n) :
    (Nat.totient n : ℤ) =
      ∑ d ∈ n.divisors, mobiusTotientChannel d n := by
  rw [← MersenneLambertLadder.sum_divisors_moebius_mul_div n hn]
  apply Finset.sum_congr rfl
  intro d hd
  rw [mobiusTotientChannel, if_pos (Nat.dvd_of_mem_divisors hd)]

/-- Along a `d`-divisible shift, the affine Möbius channel becomes a
constant multiple of the divisor indicator. -/
theorem forwardDifference_mobiusTotientChannel_of_dvd
    {d h : ℕ} (hd : 0 < d) (hdh : d ∣ h) :
    forwardDifference h (mobiusTotientChannel d) = fun n =>
      if d ∣ n then
        ArithmeticFunction.moebius d * ((h / d : ℕ) : ℤ)
      else 0 := by
  rcases hdh with ⟨k, rfl⟩
  funext n
  have hdk : d ∣ d * k := dvd_mul_right d k
  by_cases hdn : d ∣ n
  · have hdadd : d ∣ n + d * k := hdn.add hdk
    simp only [forwardDifference, mobiusTotientChannel, if_pos hdadd, if_pos hdn]
    rw [Nat.add_mul_div_left n k hd]
    rw [Nat.mul_comm d k, Nat.mul_div_left k hd]
    push_cast
    ring
  · have hdadd : ¬d ∣ n + d * k := by
      intro hdiv
      have hreorder : n + d * k = d * k + n := by omega
      rw [hreorder] at hdiv
      exact hdn ((Nat.dvd_add_iff_right hdk).mpr hdiv)
    simp [forwardDifference, mobiusTotientChannel, hdadd, hdn]

/-- **Exact old-channel cancellation.**  A Möbius divisor channel vanishes
after two shift differences whose axes are both divisible by `d`.  Thus only
channels not covered by such a divisible pair can contribute to the
rank-cube sum; no converse nonvanishing claim is made. -/
theorem rankTwo_mobiusTotientChannel_eq_zero_of_dvd
    {d h k : ℕ} (hd : 0 < d) (hdh : d ∣ h) (hdk : d ∣ k) :
    forwardDifference k (forwardDifference h (mobiusTotientChannel d)) =
      fun _ => 0 := by
  rw [forwardDifference_mobiusTotientChannel_of_dvd hd hdh]
  funext n
  simp only [forwardDifference]
  by_cases hdn : d ∣ n
  · have hdnk : d ∣ n + k := hdn.add hdk
    simp [hdn, hdnk]
  · have hdnk : ¬d ∣ n + k := by
      intro hdiv
      rw [Nat.add_comm] at hdiv
      exact hdn ((Nat.dvd_add_iff_right hdk).mpr hdiv)
    simp [hdn, hdnk]

/-- **All-rank old-channel cancellation.**  Arbitrary shifts may occur before,
between, and after two axes divisible by `d`; the whole finite-rank Möbius
channel still vanishes.  The displayed list split is an exact witness that
the two divisible axes occur in the shift cube. -/
theorem iteratedForwardDifference_mobiusTotientChannel_eq_zero_of_two_dvd
    (before between after : List ℕ) {d h k : ℕ}
    (hd : 0 < d) (hdh : d ∣ h) (hdk : d ∣ k) :
    iteratedForwardDifference
        (before ++ (h :: between ++ (k :: after)))
        (mobiusTotientChannel d) = fun _ => 0 := by
  have hcore :
      forwardDifference h (forwardDifference k (mobiusTotientChannel d)) =
        fun _ => 0 := by
    rw [forwardDifference_comm]
    exact rankTwo_mobiusTotientChannel_eq_zero_of_dvd hd hdh hdk
  have hsuffix :
      forwardDifference h
          (forwardDifference k
            (iteratedForwardDifference after (mobiusTotientChannel d))) =
        fun _ => 0 := by
    rw [forwardDifference_iteratedForwardDifference]
    rw [forwardDifference_iteratedForwardDifference]
    rw [hcore, iteratedForwardDifference_zero]
  have hmiddle :
      forwardDifference h
          (iteratedForwardDifference between
            (forwardDifference k
              (iteratedForwardDifference after (mobiusTotientChannel d)))) =
        fun _ => 0 := by
    rw [forwardDifference_iteratedForwardDifference]
    rw [hsuffix, iteratedForwardDifference_zero]
  have htail :
      iteratedForwardDifference
          (h :: between ++ (k :: after)) (mobiusTotientChannel d) =
        fun _ => 0 := by
    change forwardDifference h
        (iteratedForwardDifference (between ++ (k :: after))
          (mobiusTotientChannel d)) = fun _ => 0
    rw [iteratedForwardDifference_append]
    exact hmiddle
  rw [iteratedForwardDifference_append, htail, iteratedForwardDifference_zero]

/-! ## The LCM anchor set and its exact sparse support -/

/-- State anchors corresponding to the exact whole-ray letters at
`q * periodLcm t`, for `2 ≤ q < t`. -/
def lcmAnchorStates (t : ℕ) : Finset ℕ :=
  (Finset.Ico 2 t).image (fun q => (q - 1) * periodLcm t)

/-- The LCM pulse state with amplitude `φ(periodLcm t)`. -/
def lcmAnchorPulseState (t k : ℕ) : ℤ :=
  sparsePulseState (Nat.totient (periodLcm t) : ℤ) (lcmAnchorStates t) k

/-- The LCM pulse forcing word. -/
def lcmAnchorPulseLetter (t i : ℕ) : ℤ :=
  sparsePulseLetter (Nat.totient (periodLcm t) : ℤ) (lcmAnchorStates t) i

/-- The pulse letter is literally the dyadic coboundary of the pulse state. -/
theorem lcmAnchorPulseLetter_eq_dyadicCoboundary (t : ℕ) :
    lcmAnchorPulseLetter t = dyadicCoboundary (lcmAnchorPulseState t) := by
  funext i
  rfl

/-- The transformed state attached to an arbitrary finite shift cube. -/
def lcmAnchorFiniteRankState (t : ℕ) (shifts : List ℕ) : ℕ → ℤ :=
  iteratedForwardDifference shifts (lcmAnchorPulseState t)

/-- The transformed pulse letters attached to the same finite shift cube. -/
def lcmAnchorFiniteRankLetter (t : ℕ) (shifts : List ℕ) : ℕ → ℤ :=
  iteratedForwardDifference shifts (lcmAnchorPulseLetter t)

/-- Every finite-rank transformed pulse remains an exact dyadic coboundary. -/
theorem lcmAnchorFiniteRankLetter_eq_dyadicCoboundary
    (t : ℕ) (shifts : List ℕ) :
    lcmAnchorFiniteRankLetter t shifts =
      dyadicCoboundary (lcmAnchorFiniteRankState t shifts) := by
  unfold lcmAnchorFiniteRankLetter lcmAnchorFiniteRankState
  rw [lcmAnchorPulseLetter_eq_dyadicCoboundary,
    iteratedForwardDifference_dyadicCoboundary]

/-- Exact all-horizon terminal-state compensation for every finite-rank LCM
shift cube (indeed, for arbitrary additive shifts). -/
theorem lcmAnchorFiniteRank_clearedPrefix
    (t : ℕ) (shifts : List ℕ) (n L : ℕ) :
    dyadicClearedPrefix (lcmAnchorFiniteRankLetter t shifts) n L =
      (2 : ℤ) ^ L * lcmAnchorFiniteRankState t shifts n -
        lcmAnchorFiniteRankState t shifts (n + L) := by
  rw [lcmAnchorFiniteRankLetter_eq_dyadicCoboundary]
  exact dyadicClearedPrefix_dyadicCoboundary _ _ _

/-- Pulse state transformed by an arbitrary finite integer shift polynomial. -/
def lcmAnchorShiftPolynomialState
    (t : ℕ) (terms : List (ℕ × ℤ)) : ℕ → ℤ :=
  shiftLinearCombination terms (lcmAnchorPulseState t)

/-- Pulse letters transformed by the same shift polynomial. -/
def lcmAnchorShiftPolynomialLetter
    (t : ℕ) (terms : List (ℕ × ℤ)) : ℕ → ℤ :=
  shiftLinearCombination terms (lcmAnchorPulseLetter t)

/-- Every finite integer shift polynomial preserves the exact coboundary
relation. -/
theorem lcmAnchorShiftPolynomialLetter_eq_dyadicCoboundary
    (t : ℕ) (terms : List (ℕ × ℤ)) :
    lcmAnchorShiftPolynomialLetter t terms =
      dyadicCoboundary (lcmAnchorShiftPolynomialState t terms) := by
  unfold lcmAnchorShiftPolynomialLetter lcmAnchorShiftPolynomialState
  rw [lcmAnchorPulseLetter_eq_dyadicCoboundary,
    shiftLinearCombination_dyadicCoboundary]

/-- Exact all-horizon terminal-state compensation for every finite shift
polynomial, including every commensurate finite-rank LCM cube normal form. -/
theorem lcmAnchorShiftPolynomial_clearedPrefix
    (t : ℕ) (terms : List (ℕ × ℤ)) (n L : ℕ) :
    dyadicClearedPrefix (lcmAnchorShiftPolynomialLetter t terms) n L =
      (2 : ℤ) ^ L * lcmAnchorShiftPolynomialState t terms n -
        lcmAnchorShiftPolynomialState t terms (n + L) := by
  rw [lcmAnchorShiftPolynomialLetter_eq_dyadicCoboundary]
  exact dyadicClearedPrefix_dyadicCoboundary _ _ _

lemma two_le_periodLcm {t : ℕ} (ht : 3 ≤ t) : 2 ≤ periodLcm t := by
  exact Nat.le_of_dvd (periodLcm_pos t)
    (dvd_periodLcm (by omega) (by omega))

lemma lcmAnchorStates_mem {t q : ℕ} (hq2 : 2 ≤ q) (hqt : q < t) :
    (q - 1) * periodLcm t ∈ lcmAnchorStates t := by
  apply Finset.mem_image.mpr
  exact ⟨q, Finset.mem_Ico.mpr ⟨hq2, hqt⟩, rfl⟩

/-- Distinct LCM state anchors are separated by at least two positions. -/
theorem lcmAnchorStates_pairwise_gap {t x y : ℕ} (ht : 3 ≤ t)
    (hx : x ∈ lcmAnchorStates t) (hy : y ∈ lcmAnchorStates t)
    (hxy : x ≠ y) :
    x + 2 ≤ y ∨ y + 2 ≤ x := by
  rcases Finset.mem_image.mp hx with ⟨q, hq, rfl⟩
  rcases Finset.mem_image.mp hy with ⟨r, hr, rfl⟩
  have hqr : q ≠ r := by
    intro h
    subst r
    exact hxy rfl
  have hH2 : 2 ≤ periodLcm t := two_le_periodLcm ht
  rcases lt_or_gt_of_ne hqr with hlt | hgt
  · left
    have hstep : q - 1 + 1 ≤ r - 1 := by
      have hq2 := (Finset.mem_Ico.mp hq).1
      omega
    calc
      (q - 1) * periodLcm t + 2 ≤
          (q - 1) * periodLcm t + periodLcm t :=
        Nat.add_le_add_left hH2 _
      _ = (q - 1 + 1) * periodLcm t := by ring
      _ ≤ (r - 1) * periodLcm t := Nat.mul_le_mul_right _ hstep
  · right
    have hstep : r - 1 + 1 ≤ q - 1 := by
      have hr2 := (Finset.mem_Ico.mp hr).1
      omega
    calc
      (r - 1) * periodLcm t + 2 ≤
          (r - 1) * periodLcm t + periodLcm t :=
        Nat.add_le_add_left hH2 _
      _ = (r - 1 + 1) * periodLcm t := by ring
      _ ≤ (q - 1) * periodLcm t := Nat.mul_le_mul_right _ hstep

lemma lcmAnchorStates_succ_not_mem {t x : ℕ} (ht : 3 ≤ t)
    (hx : x ∈ lcmAnchorStates t) : x + 1 ∉ lcmAnchorStates t := by
  intro hs
  have hne : x ≠ x + 1 := by omega
  rcases lcmAnchorStates_pairwise_gap ht hx hs hne with h | h <;> omega

lemma lcmAnchorStates_pred_not_mem {t x : ℕ} (ht : 3 ≤ t)
    (hx : x ∈ lcmAnchorStates t) (hxpos : 0 < x) :
    x - 1 ∉ lcmAnchorStates t := by
  intro hp
  have hne : x - 1 ≠ x := by omega
  rcases lcmAnchorStates_pairwise_gap ht hp hx hne with h | h <;> omega

/-- Explicit support formula: an anchor-entry letter is `A`, an anchor-exit
letter is `-2A`, and every other letter is zero. -/
theorem lcmAnchorPulseLetter_eq (t i : ℕ) (ht : 3 ≤ t) :
    lcmAnchorPulseLetter t i =
      if i + 1 ∈ lcmAnchorStates t then
        (Nat.totient (periodLcm t) : ℤ)
      else if i ∈ lcmAnchorStates t then
        -2 * (Nat.totient (periodLcm t) : ℤ)
      else 0 := by
  by_cases hi : i ∈ lcmAnchorStates t
  · have hs : i + 1 ∉ lcmAnchorStates t :=
      lcmAnchorStates_succ_not_mem ht hi
    simp [lcmAnchorPulseLetter, sparsePulseLetter, sparsePulseState, hi, hs]
  · by_cases hs : i + 1 ∈ lcmAnchorStates t
    · simp [lcmAnchorPulseLetter, sparsePulseLetter, sparsePulseState, hi, hs]
    · simp [lcmAnchorPulseLetter, sparsePulseLetter, sparsePulseState, hi, hs]

/-- The pulse letter entering every prescribed state anchor is exactly `φ(H)`. -/
theorem lcmAnchorPulse_letter_at_anchor {t q : ℕ} (ht : 3 ≤ t)
    (hq2 : 2 ≤ q) (hqt : q < t) :
    lcmAnchorPulseLetter t ((q - 1) * periodLcm t - 1) =
      (Nat.totient (periodLcm t) : ℤ) := by
  let x := (q - 1) * periodLcm t
  have hx : x ∈ lcmAnchorStates t := lcmAnchorStates_mem hq2 hqt
  have hxpos : 0 < x := by
    dsimp [x]
    exact Nat.mul_pos (by omega) (periodLcm_pos t)
  have hp : x - 1 ∉ lcmAnchorStates t :=
    lcmAnchorStates_pred_not_mem ht hx hxpos
  have hsucc : x - 1 + 1 = x := by omega
  simp [lcmAnchorPulseLetter, sparsePulseLetter, sparsePulseState,
    x, hp, hsucc, hx]

/-- The compensation letter immediately after every anchor is `-2φ(H)`. -/
theorem lcmAnchorPulse_letter_after_anchor {t q : ℕ} (ht : 3 ≤ t)
    (hq2 : 2 ≤ q) (hqt : q < t) :
    lcmAnchorPulseLetter t ((q - 1) * periodLcm t) =
      -2 * (Nat.totient (periodLcm t) : ℤ) := by
  let x := (q - 1) * periodLcm t
  have hx : x ∈ lcmAnchorStates t := lcmAnchorStates_mem hq2 hqt
  have hs : x + 1 ∉ lcmAnchorStates t :=
    lcmAnchorStates_succ_not_mem ht hx
  simp [lcmAnchorPulseLetter, sparsePulseLetter, sparsePulseState, x, hx, hs]

/-! ## Exact arithmetic anchors -/

/-- If `q ∣ H`, multiplying `H` by `q` adds only already-present prime
factors, so the totient scales by exactly `q`. -/
theorem totient_mul_eq_left_mul_totient_of_dvd {q H : ℕ} (hqH : q ∣ H) :
    Nat.totient (q * H) = q * Nat.totient H := by
  induction q using Nat.strong_induction_on with
  | h q ih =>
      by_cases hq0 : q = 0
      · subst q
        simp_all
      by_cases hq1 : q = 1
      · subst q
        simp
      obtain ⟨p, hp, hpq⟩ := Nat.exists_prime_and_dvd hq1
      have hfactor : p * (q / p) = q := Nat.mul_div_cancel' hpq
      have hqpos : 0 < q := Nat.pos_of_ne_zero hq0
      have hrlt : q / p < q := Nat.div_lt_self hqpos hp.one_lt
      have hrdvdq : q / p ∣ q := by
        refine ⟨p, ?_⟩
        rw [Nat.mul_comm, hfactor]
      have hrdvdH : q / p ∣ H := hrdvdq.trans hqH
      have hpH : p ∣ H := hpq.trans hqH
      calc
        Nat.totient (q * H) = Nat.totient (p * ((q / p) * H)) := by
          rw [← Nat.mul_assoc, hfactor]
        _ = p * Nat.totient ((q / p) * H) :=
          Nat.totient_mul_of_prime_of_dvd hp (hpH.mul_left (q / p))
        _ = p * ((q / p) * Nat.totient H) := by
          rw [ih (q / p) hrlt hrdvdH]
        _ = (p * (q / p)) * Nat.totient H := by ring
        _ = q * Nat.totient H := by rw [hfactor]

/-- Every prescribed whole-ray forcing letter is an exact arithmetic anchor. -/
theorem deltaTotient_periodLcm_anchor {t q : ℕ}
    (hq2 : 2 ≤ q) (hqt : q < t) :
    deltaTotient (periodLcm t) (q * periodLcm t) =
      (Nat.totient (periodLcm t) : ℤ) := by
  have hqH : q ∣ periodLcm t :=
    dvd_periodLcm (by omega) (by omega)
  have hq1H : q + 1 ∣ periodLcm t :=
    dvd_periodLcm (by omega) (by omega)
  have hqφ := totient_mul_eq_left_mul_totient_of_dvd hqH
  have hq1φ := totient_mul_eq_left_mul_totient_of_dvd hq1H
  unfold deltaTotient
  rw [show q * periodLcm t + periodLcm t =
      (q + 1) * periodLcm t by ring, hq1φ, hqφ]
  push_cast
  ring

/-- The synthetic word agrees exactly with every sparse whole-ray anchor. -/
theorem lcmAnchorPulse_letter_eq_deltaTotient {t q : ℕ} (ht : 3 ≤ t)
    (hq2 : 2 ≤ q) (hqt : q < t) :
    lcmAnchorPulseLetter t ((q - 1) * periodLcm t - 1) =
      deltaTotient (periodLcm t) (q * periodLcm t) := by
  rw [lcmAnchorPulse_letter_at_anchor ht hq2 hqt,
    deltaTotient_periodLcm_anchor hq2 hqt]

/-! ## Bounds, factor ideals, and the formal no-go -/

theorem lcmAnchorPulse_recurrence (t i : ℕ) :
    lcmAnchorPulseState t (i + 1) =
      2 * lcmAnchorPulseState t i - lcmAnchorPulseLetter t i := by
  exact sparsePulse_recurrence _ _ _

theorem lcmAnchorPulse_dvd_totient_periodLcm (t i : ℕ) :
    (Nat.totient (periodLcm t) : ℤ) ∣ lcmAnchorPulseLetter t i := by
  exact sparsePulse_dvd_letter _ _ _

/-- Every lower factor ideal coming from a divisor `j ∣ H` is absorbed by
the pulse word. -/
theorem lcmAnchorPulse_dvd_totient_of_dvd {t j : ℕ} (hj : j ∣ periodLcm t)
    (i : ℕ) :
    (Nat.totient j : ℤ) ∣ lcmAnchorPulseLetter t i := by
  have hφ : Nat.totient j ∣ Nat.totient (periodLcm t) :=
    Nat.totient_dvd_of_dvd hj
  have hφz : (Nat.totient j : ℤ) ∣ (Nat.totient (periodLcm t) : ℤ) := by
    rcases hφ with ⟨k, hk⟩
    refine ⟨k, ?_⟩
    exact_mod_cast hk
  exact hφz.trans (lcmAnchorPulse_dvd_totient_periodLcm t i)

/-- Finite shift rank preserves divisibility by the scale totient. -/
theorem lcmAnchorFiniteRank_dvd_totient_periodLcm
    (t : ℕ) (shifts : List ℕ) (i : ℕ) :
    (Nat.totient (periodLcm t) : ℤ) ∣ lcmAnchorFiniteRankLetter t shifts i := by
  unfold lcmAnchorFiniteRankLetter
  exact dvd_iteratedForwardDifference _ _
    (lcmAnchorPulse_dvd_totient_periodLcm t) shifts i

/-- Every lower factor ideal remains absorbed after arbitrary finite shift
rank. -/
theorem lcmAnchorFiniteRank_dvd_totient_of_dvd {t j : ℕ}
    (hj : j ∣ periodLcm t) (shifts : List ℕ) (i : ℕ) :
    (Nat.totient j : ℤ) ∣ lcmAnchorFiniteRankLetter t shifts i := by
  unfold lcmAnchorFiniteRankLetter
  exact dvd_iteratedForwardDifference _ _
    (lcmAnchorPulse_dvd_totient_of_dvd hj) shifts i

/-- Generic rank bound for the transformed pulse state.  Sharper
commensurate bounds are evaluator-level refinements; this symbolic bound is
uniform over arbitrary shifts. -/
theorem lcmAnchorFiniteRank_state_bound (t : ℕ) (shifts : List ℕ) (i : ℕ) :
    |lcmAnchorFiniteRankState t shifts i| ≤
      (2 : ℤ) ^ shifts.length * |(Nat.totient (periodLcm t) : ℤ)| := by
  unfold lcmAnchorFiniteRankState lcmAnchorPulseState
  exact abs_iteratedForwardDifference_le _ _
    (abs_sparsePulseState_le _ _) shifts i

/-- Generic rank bound for the transformed pulse letters. -/
theorem lcmAnchorFiniteRank_letter_bound (t : ℕ) (shifts : List ℕ) (i : ℕ) :
    |lcmAnchorFiniteRankLetter t shifts i| ≤
      (2 : ℤ) ^ shifts.length *
        (2 * |(Nat.totient (periodLcm t) : ℤ)|) := by
  unfold lcmAnchorFiniteRankLetter lcmAnchorPulseLetter
  exact abs_iteratedForwardDifference_le _ _
    (abs_sparsePulseLetter_le _ _) shifts i

/-- Finite shift polynomials preserve divisibility by the scale totient. -/
theorem lcmAnchorShiftPolynomial_dvd_totient_periodLcm
    (t : ℕ) (terms : List (ℕ × ℤ)) (i : ℕ) :
    (Nat.totient (periodLcm t) : ℤ) ∣
      lcmAnchorShiftPolynomialLetter t terms i := by
  unfold lcmAnchorShiftPolynomialLetter
  exact dvd_shiftLinearCombination _ _
    (lcmAnchorPulse_dvd_totient_periodLcm t) terms i

/-- Every lower factor ideal remains absorbed under a finite shift
polynomial. -/
theorem lcmAnchorShiftPolynomial_dvd_totient_of_dvd {t j : ℕ}
    (hj : j ∣ periodLcm t) (terms : List (ℕ × ℤ)) (i : ℕ) :
    (Nat.totient j : ℤ) ∣ lcmAnchorShiftPolynomialLetter t terms i := by
  unfold lcmAnchorShiftPolynomialLetter
  exact dvd_shiftLinearCombination _ _
    (lcmAnchorPulse_dvd_totient_of_dvd hj) terms i

/-- Uniform state bound for a transformed shift polynomial. -/
theorem lcmAnchorShiftPolynomial_state_bound
    (t : ℕ) (terms : List (ℕ × ℤ)) (i : ℕ) :
    |lcmAnchorShiftPolynomialState t terms i| ≤
      shiftLinearWeight terms * |(Nat.totient (periodLcm t) : ℤ)| := by
  unfold lcmAnchorShiftPolynomialState lcmAnchorPulseState
  exact abs_shiftLinearCombination_le _ _
    (abs_sparsePulseState_le _ _) terms i

/-- Uniform letter bound for a transformed shift polynomial. -/
theorem lcmAnchorShiftPolynomial_letter_bound
    (t : ℕ) (terms : List (ℕ × ℤ)) (i : ℕ) :
    |lcmAnchorShiftPolynomialLetter t terms i| ≤
      shiftLinearWeight terms *
        (2 * |(Nat.totient (periodLcm t) : ℤ)|) := by
  unfold lcmAnchorShiftPolynomialLetter lcmAnchorPulseLetter
  exact abs_shiftLinearCombination_le _ _
    (abs_sparsePulseLetter_le _ _) terms i

theorem lcmAnchorPulse_letter_bound (t i : ℕ) :
    |lcmAnchorPulseLetter t i| ≤
      (2 * periodLcm t + i + 1 : ℕ) := by
  have hletter := abs_sparsePulseLetter_le
    (Nat.totient (periodLcm t) : ℤ) (lcmAnchorStates t) i
  have hφnonneg : (0 : ℤ) ≤ Nat.totient (periodLcm t) := by positivity
  have hφle : (Nat.totient (periodLcm t) : ℤ) ≤ periodLcm t := by
    exact_mod_cast Nat.totient_le (periodLcm t)
  change |sparsePulseLetter (Nat.totient (periodLcm t) : ℤ)
      (lcmAnchorStates t) i| ≤ ((2 * periodLcm t + i + 1 : ℕ) : ℤ)
  rw [abs_of_nonneg hφnonneg] at hletter
  push_cast
  omega

/-- The synthetic state remains strictly inside every diagonal carry strip. -/
theorem lcmAnchorPulse_strict_survivor (t i : ℕ) :
    |lcmAnchorPulseState t i| <
      (2 * periodLcm t + i + 2 : ℕ) := by
  have hstate := abs_sparsePulseState_le
    (Nat.totient (periodLcm t) : ℤ) (lcmAnchorStates t) i
  have hφnonneg : (0 : ℤ) ≤ Nat.totient (periodLcm t) := by positivity
  have hφle : (Nat.totient (periodLcm t) : ℤ) ≤ periodLcm t := by
    exact_mod_cast Nat.totient_le (periodLcm t)
  have hHpos : 0 < periodLcm t := periodLcm_pos t
  change |sparsePulseState (Nat.totient (periodLcm t) : ℤ)
      (lcmAnchorStates t) i| < ((2 * periodLcm t + i + 2 : ℕ) : ℤ)
  rw [abs_of_nonneg hφnonneg] at hstate
  push_cast
  omega

/-- **All-rank shift-algebra no-go.**  For every `t ≥ 3`, one nonzero
synthetic pulse simultaneously compensates every finite integer shift
polynomial.
Each transformed word remains a dyadic coboundary, every cleared prefix is
cancelled exactly by its terminal transformed state, every lower factor ideal
is inherited, and uniform coefficient-weight bounds remain available.

The shifts need not be commensurate.  Hence the theorem covers every finite
family of rank-two/rank-three LCM cubes, arbitrary finite rank, and each entry
of a matrix built from finitely many such linear observations.  It makes no
claim about nonlinear combinations such as determinants, and it does not
assert that the base or transformed letters are actual totient differences. -/
theorem lcm_factorIdeal_finiteRank_shiftAlgebra_not_sufficient
    (t : ℕ) (ht : 3 ≤ t) :
    ∃ c a : ℕ → ℤ,
      (∃ k, c k ≠ 0) ∧
      (∀ i, a i = dyadicCoboundary c i) ∧
      ∀ terms : List (ℕ × ℤ),
        ∃ d b : ℕ → ℤ,
          (∀ i, d i = shiftLinearCombination terms c i) ∧
          (∀ i, b i = shiftLinearCombination terms a i) ∧
          (∀ i, b i = dyadicCoboundary d i) ∧
          (∀ n L, dyadicClearedPrefix b n L =
            (2 : ℤ) ^ L * d n - d (n + L)) ∧
          (∀ i, (Nat.totient (periodLcm t) : ℤ) ∣ b i) ∧
          (∀ j, j ∣ periodLcm t → ∀ i, (Nat.totient j : ℤ) ∣ b i) ∧
          (∀ i, |d i| ≤ shiftLinearWeight terms *
            |(Nat.totient (periodLcm t) : ℤ)|) ∧
          ∀ i, |b i| ≤ shiftLinearWeight terms *
            (2 * |(Nat.totient (periodLcm t) : ℤ)|) := by
  refine ⟨lcmAnchorPulseState t, lcmAnchorPulseLetter t, ?_, ?_, ?_⟩
  · let x := periodLcm t
    have hx : x ∈ lcmAnchorStates t := by
      simpa [x] using lcmAnchorStates_mem (t := t) (q := 2) (by omega) (by omega)
    have hφpos : 0 < Nat.totient (periodLcm t) :=
      Nat.totient_pos.mpr (periodLcm_pos t)
    have hφne : (Nat.totient (periodLcm t) : ℤ) ≠ 0 := by
      exact_mod_cast hφpos.ne'
    refine ⟨x, ?_⟩
    change sparsePulseState (Nat.totient (periodLcm t) : ℤ)
      (lcmAnchorStates t) x ≠ 0
    rw [sparsePulseState, if_pos hx]
    simpa using hφne
  · intro i
    exact congrFun (lcmAnchorPulseLetter_eq_dyadicCoboundary t) i
  · intro terms
    refine ⟨lcmAnchorShiftPolynomialState t terms,
      lcmAnchorShiftPolynomialLetter t terms, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
    · intro i
      rfl
    · intro i
      rfl
    · intro i
      exact congrFun (lcmAnchorShiftPolynomialLetter_eq_dyadicCoboundary t terms) i
    · exact lcmAnchorShiftPolynomial_clearedPrefix t terms
    · exact lcmAnchorShiftPolynomial_dvd_totient_periodLcm t terms
    · intro j hj i
      exact lcmAnchorShiftPolynomial_dvd_totient_of_dvd hj terms i
    · exact lcmAnchorShiftPolynomial_state_bound t terms
    · exact lcmAnchorShiftPolynomial_letter_bound t terms

/-- The exact hypothesis class defeated by the sparse pulse. -/
def LcmFactorIdealAnchorAdmissible (t : ℕ)
    (c a : ℕ → ℤ) : Prop :=
  (∀ i, c (i + 1) = 2 * c i - a i) ∧
  (∀ i, (Nat.totient (periodLcm t) : ℤ) ∣ a i) ∧
  (∀ j, j ∣ periodLcm t → ∀ i, (Nat.totient j : ℤ) ∣ a i) ∧
  (∀ i, |a i| ≤ (2 * periodLcm t + i + 1 : ℕ)) ∧
  (∀ i, |c i| < (2 * periodLcm t + i + 2 : ℕ)) ∧
  (∀ q, 2 ≤ q → q < t →
    a ((q - 1) * periodLcm t - 1) =
      deltaTotient (periodLcm t) (q * periodLcm t))

/-- **LCM factor-ideal sparse-anchor no-go.**  For every `t ≥ 3` there is a
nonzero synthetic carry orbit satisfying the exact affine recurrence, all
homogeneous lower factor ideals, the natural letter and strip bounds, and
every prescribed whole-ray anchor.  It survives every finite horizon.

This does not assert arithmetic realisability of the compensation letters;
it proves that the named factor-only hypotheses are not sufficient. -/
theorem lcm_factorIdeal_sparseAnchor_not_sufficient (t : ℕ) (ht : 3 ≤ t) :
    ∃ c a : ℕ → ℤ,
      LcmFactorIdealAnchorAdmissible t c a ∧
      (∃ k, c k ≠ 0) ∧
      ∀ K i, i ≤ K → |c i| < (2 * periodLcm t + i + 2 : ℕ) := by
  refine ⟨lcmAnchorPulseState t, lcmAnchorPulseLetter t, ?_, ?_, ?_⟩
  · exact ⟨lcmAnchorPulse_recurrence t,
      lcmAnchorPulse_dvd_totient_periodLcm t,
      fun j hj i => lcmAnchorPulse_dvd_totient_of_dvd hj i,
      lcmAnchorPulse_letter_bound t,
      lcmAnchorPulse_strict_survivor t,
      fun q hq2 hqt => lcmAnchorPulse_letter_eq_deltaTotient ht hq2 hqt⟩
  · let x := periodLcm t
    have hx : x ∈ lcmAnchorStates t := by
      simpa [x] using lcmAnchorStates_mem (t := t) (q := 2) (by omega) (by omega)
    have hφpos : 0 < Nat.totient (periodLcm t) :=
      Nat.totient_pos.mpr (periodLcm_pos t)
    have hφne : (Nat.totient (periodLcm t) : ℤ) ≠ 0 := by
      exact_mod_cast hφpos.ne'
    refine ⟨x, ?_⟩
    change sparsePulseState (Nat.totient (periodLcm t) : ℤ)
      (lcmAnchorStates t) x ≠ 0
    rw [sparsePulseState, if_pos hx]
    simpa using hφne
  · intro K i _
    exact lcmAnchorPulse_strict_survivor t i

/-! ## Smallest closed witness: `t = 3`, `H = 6`, `A = 2` -/

theorem lcmAnchorPulse_t3_letters :
    lcmAnchorPulseLetter 3 5 = 2 ∧
      lcmAnchorPulseLetter 3 6 = -4 := by
  have hφ6 : Nat.totient 6 = 2 := by decide
  norm_num [lcmAnchorPulseLetter, sparsePulseLetter, sparsePulseState,
    lcmAnchorStates, periodLcm, hφ6]

theorem lcmAnchorPulse_t3_strict_survivor (i : ℕ) :
    |lcmAnchorPulseState 3 i| < (12 + i + 2 : ℕ) := by
  simpa [show periodLcm 3 = 6 by norm_num [periodLcm]] using
    lcmAnchorPulse_strict_survivor 3 i

#print axioms sparsePulse_recurrence
#print axioms affineBinaryOrbit_sparsePulseInput
#print axioms totient_eq_sum_mobiusTotientChannel
#print axioms rankTwo_mobiusTotientChannel_eq_zero_of_dvd
#print axioms iteratedForwardDifference_mobiusTotientChannel_eq_zero_of_two_dvd
#print axioms deltaTotient_periodLcm_anchor
#print axioms lcmAnchorPulse_letter_eq_deltaTotient
#print axioms lcm_factorIdeal_sparseAnchor_not_sufficient
#print axioms lcm_factorIdeal_finiteRank_shiftAlgebra_not_sufficient
#print axioms lcmAnchorPulse_t3_letters

end TotientTailPeriodKiller
end Erdos249257
