#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Will Cook
# SPDX-License-Identifier: Apache-2.0
"""Generate short, unique display labels for Lean source links in the papers."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
PAPER_DIR = ROOT / "paper"
PAPERS = (
    PAPER_DIR / "erdos249-257-exposition.tex",
    PAPER_DIR / "erdos249-transport-curvature.tex",
)
OUTPUT = PAPER_DIR / "module-aliases.tex"
LINK_RE = re.compile(r"\\(?:lrefx?|lloc)\{([^}]+\.lean)\}")


def camel_components(stem: str) -> list[str]:
    """Split CamelCase while keeping compact suffixes such as T43 together."""
    separated = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", stem)
    separated = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", separated)
    components = separated.split()
    if not components or "".join(components) != stem:
        raise ValueError(f"cannot split module stem {stem!r}")
    return components


def module_alias(module: str) -> str:
    """Use up to the first three characters of every CamelCase component."""
    stem = module.removesuffix(".lean")
    return "".join(component if len(component) <= 3 else component[:3]
                   for component in camel_components(stem))


def referenced_modules() -> list[str]:
    modules: set[str] = set()
    for paper in PAPERS:
        modules.update(LINK_RE.findall(paper.read_text(encoding="utf-8")))
    return sorted(modules)


def render(modules: list[str]) -> str:
    aliases = {module: module_alias(module) for module in modules}
    collisions: dict[str, list[str]] = {}
    for module, alias in aliases.items():
        collisions.setdefault(alias, []).append(module)
    duplicates = {alias: names for alias, names in collisions.items() if len(names) > 1}
    if duplicates:
        details = "; ".join(f"{alias}: {', '.join(names)}"
                            for alias, names in sorted(duplicates.items()))
        raise ValueError(f"paper module alias collision(s): {details}")

    lines = [
        "% SPDX-FileCopyrightText: 2026 Will Cook",
        "% SPDX-License-Identifier: CC-BY-4.0",
        "% Generated by scripts/build_paper_module_aliases.py; do not edit.",
        "% Each CamelCase component contributes at most its first three characters.",
        r"\newcommand{\modulesigil}[1]{\csname modulesigil@#1\endcsname}",
    ]
    for module, alias in aliases.items():
        lines.append(
            rf"\expandafter\def\csname modulesigil@{module}\endcsname{{{alias}}}"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()

    modules = referenced_modules()
    expected = render(modules)
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if actual != expected:
            print("paper/module-aliases.tex is stale; run python3 scripts/build_paper_module_aliases.py")
            return 1
        print(f"paper module aliases current: {len(modules)} unique modules")
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(modules)} unique module aliases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
