#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Will Cook
# SPDX-License-Identifier: Apache-2.0
"""Generate short, unique display labels for Lean source links in the papers."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
PAPER_DIR = ROOT / "paper"
PAPERS = (
    PAPER_DIR / "erdos249-257-exposition.tex",
    PAPER_DIR / "erdos249-transport-curvature.tex",
)
OUTPUT = PAPER_DIR / "module-aliases.tex"
JSON_OUTPUT = PAPER_DIR / "module-aliases.json"
LINK_RE = re.compile(r"\\(?:lrefx?|lloc)\{([^}]+\.lean)\}")


def camel_components(stem: str) -> list[str]:
    """Split CamelCase while keeping compact suffixes such as T43 together."""
    separated = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", stem)
    separated = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", separated)
    components = separated.split()
    if not components or "".join(components) != stem:
        raise ValueError(f"cannot split module stem {stem!r}")
    return components


def module_alias(module: str) -> str:
    """Use up to the first three characters of every CamelCase component."""
    stem = module.removesuffix(".lean")
    return "".join(component if len(component) <= 3 else component[:3]
                   for component in camel_components(stem))


def referenced_modules() -> list[str]:
    modules: set[str] = set()
    for paper in PAPERS:
        modules.update(LINK_RE.findall(paper.read_text(encoding="utf-8")))
    return sorted(modules)


def aliases_for_modules(modules: list[str]) -> dict[str, str]:
    aliases = {module: module_alias(module) for module in modules}
    collisions: dict[str, list[str]] = {}
    for module, alias in aliases.items():
        collisions.setdefault(alias, []).append(module)
    duplicates = {alias: names for alias, names in collisions.items() if len(names) > 1}
    if duplicates:
        details = "; ".join(f"{alias}: {', '.join(names)}"
                            for alias, names in sorted(duplicates.items()))
        raise ValueError(f"paper module alias collision(s): {details}")
    return aliases


def render_tex(aliases: dict[str, str]) -> str:

    lines = [
        "% SPDX-FileCopyrightText: 2026 Will Cook",
        "% SPDX-License-Identifier: CC-BY-4.0",
        "% Generated by scripts/build_paper_module_aliases.py; do not edit.",
        "% Each CamelCase component contributes at most its first three characters.",
        r"\newcommand{\modulesigil}[1]{\csname modulesigil@#1\endcsname}",
    ]
    for module, alias in aliases.items():
        lines.append(
            rf"\expandafter\def\csname modulesigil@{module}\endcsname{{{alias}}}"
        )
    return "\n".join(lines) + "\n"


def render_json(aliases: dict[str, str]) -> str:
    payload = {
        "schema": "erdos249257-paper-module-aliases/1",
        "artifact_role": "paper_sigil_to_lean_module_navigation_crosswalk",
        "authority_posture": "generated_navigation_projection_not_proof_authority",
        "heuristic": "Each CamelCase component contributes at most its first three characters.",
        "alias_count": len(aliases),
        "aliases": [
            {
                "sigil": alias,
                "module": module,
                "path": f"Erdos249257/{module}",
            }
            for module, alias in aliases.items()
        ],
        "validation": "python3 scripts/build_paper_module_aliases.py --check",
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()

    modules = referenced_modules()
    aliases = aliases_for_modules(modules)
    expected_tex = render_tex(aliases)
    expected_json = render_json(aliases)
    if args.check:
        actual_tex = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        actual_json = JSON_OUTPUT.read_text(encoding="utf-8") if JSON_OUTPUT.is_file() else ""
        stale = []
        if actual_tex != expected_tex:
            stale.append(str(OUTPUT.relative_to(ROOT)))
        if actual_json != expected_json:
            stale.append(str(JSON_OUTPUT.relative_to(ROOT)))
        if stale:
            print(f"{', '.join(stale)} stale; run python3 scripts/build_paper_module_aliases.py")
            return 1
        print(f"paper module aliases current: {len(modules)} unique modules")
        return 0

    OUTPUT.write_text(expected_tex, encoding="utf-8")
    JSON_OUTPUT.write_text(expected_json, encoding="utf-8")
    print(
        f"wrote {OUTPUT.relative_to(ROOT)} and {JSON_OUTPUT.relative_to(ROOT)} "
        f"with {len(modules)} unique module aliases"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
